###
# @name register
POST http://localhost:4000/user/register
Content-Type: application/json

{
    "email":"a3@b.c",
    "password":"abc",
    "name":"a2"
}

###
# @name login
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "email":"a3@b.c",
    "password":"abc"
}

###

@authToken = {{login.response.body.$.accessToken}}

###

GET http://localhost:4000/user/my-account
Authorization: Bearer {{authToken}}

###

GET http://localhost:4000/user/user-account?email=a@b.c


###
PUT http://localhost:4000/user/update
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "password":"abc"
}

###
POST http://localhost:4000/procedure/create
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name":"Sample InnerInn Directory-a3",
    "parent":"5ea5fc1ab4323858a2c381bf"
}

###
PUT http://localhost:4000/procedure/update
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "id":"5ea5ceafc351ac54197f3ba9",
    "name":"Sample Directory-Updated",
    "shareType":"private"
}
###

GET http://localhost:4000/procedure/list
Authorization: Bearer {{authToken}}

###
GET http://localhost:4000/procedure/list/my
Authorization: Bearer {{authToken}}

###
# @name queryCreator
GET http://localhost:4000/procedure/list/user?email=a3@b.c
Authorization: Bearer {{authToken}}

###

# @name queryCreator
GET http://localhost:4000/procedure/list/shared
Authorization: Bearer {{authToken}}

###

GET http://localhost:4000/procedure/list/child?id=5ea5d4c750443355b435a41b

###
GET http://localhost:4000/procedure/read
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "id":"5ea5ceafc351ac54197f3ba9"
}
###
a (private)=> 5ea5ceafc351ac54197f3ba9
a3 (public)=> 5ea5d4c750443355b435a41b
###
PUT http://localhost:4000/procedure/share/give
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "id":"5ea5ceafc351ac54197f3ba9",
    "email":"a3@b.c"
}

###
PUT http://localhost:4000/procedure/share/remove
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "id":"5ea5ceafc351ac54197f3ba9",
    "email":"a3@b.c"
}